name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo bash ./setup.sh

      - name: ros2 doctor
        run: |
          export PATH=$(brew --prefix)/opt/python@3.11/libexec/bin:$PATH
          source install/setup.zsh
          ros2 doctor
